# Generated by Django 5.2 on 2025-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apy',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
